name: Surge Development

on:
  push:
    branches: [ dev ]

jobs:
  my-job:
    name: Surge Development
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Install node version 12
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'

      # Install npm packages
      - name: Install packages
        run: npm install

      - name: Install Gatsby
        run: npm install -g gatsby-cli

      # Build Gastby app
      - name: Build the app
        run: gatsby build

      # Install Surge 
      - name: Install Surge
        run: npm install -g surge

      # Deploy to the defined URL using the token
      - name: Deploy to surge
        run: surge ./public reikoforpcc.surge.sh --token ${{ secrets.surge_token }}
